
CREATE TABLE admin_users (
  id TEXT PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE user_credits ADD COLUMN plan TEXT DEFAULT 'Basic';
ALTER TABLE user_credits ADD COLUMN is_active BOOLEAN DEFAULT TRUE;
